version: "3.5"


services:
  nodejs:
    build: 
      context: ./docker
    entrypoint: /blackfire/docker/entrypoint.sh
    command: /true
    working_dir: /blackfire
    volumes:
      - ./:/blackfire
      - /etc/passwd:/etc/passwd:ro
      - /etc/secret/package-cloud.sh:/etc/secret/package-cloud.sh:ro
