name: release prod

on:
  push:
    tags:
      - 'v*'

jobs:
  coding-style:
    name: Probe NodeJs - Code Style
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: latest

      - run: |
          make eslint

  unit-tests:
    name: Probe Node.js ${{ matrix.version }} - Unit tests
    runs-on: ubuntu-latest
    needs: coding-style
    timeout-minutes: 3
    strategy:
      fail-fast: false
      matrix:
        version:
        - 18
        - 20
        - 21
        - 22
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.version }}

      - run: |
          make test

  release:
    name: Probe NodeJs - Release
    runs-on: ubuntu-latest
    needs: unit-tests
    timeout-minutes: 3
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: latest

      - run: |
          ./release.sh
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          TAG: ${{ github.ref_name }}
